### ISSUE TITLE
database server to support OHDSI stack

### ISSUE THREAD

**Issue by qcaas-nhs-sjt** [lsc-sde/k8s-iac#50]
As architect, I would like somewhere to store data for the OHDSI stack

**Comment by qcaas-nhs-sjt** [comment]
@vvcb , @PaulWoodhouseLTH 

I've been investigating the OHDSI stack and to facilitate the creation of the OHDSI stack on the SDE we will need to provision a database server on each of the environments. We've got a number of options and benefits/drawbacks for each.  According to the current documentation the docker images currently support PostgreSQL and MySQL, though it does look like the core applications can also be setup on MSSQL, though I've not tested this with the container image, we may need to create a version of the container image with the MSSQL drivers on it.

Postgres Single Server:
* This is currently on it's way out, they are suggesting we should look to upgrade to flexible servers ASAP
* To do so we will need a new private dns zone creating privatelink.postgres.database.azure.com by pheonix
* Pricing wise for a basic general purpose instance we're looking at approximately £90 per month + dev/sandbox environment costs of approximately £50 per month. These estimates are not based on real usage and may increase

Postgres Flexible Servers:
* Private Endpoints for this are currently in preview, so aren't really recommended for production use at the moment. Not sure when these are due to go into GA
* To do so we will need a new private dns zone creating privatelink.postgres.database.azure.com by pheonix 
* Pricing wise for a basic general purpose instance we're looking at approximately £120 per month + dev/sandbox environment costs of approximately £30 per month. These estimates are not based on real usage and may increase

MySQL Flexible Server:
* To do so we will need a new private dns zone creating privatelink.mysql.database.azure.com by pheonix 
* We will need to figure out how to build the mysql database and deploy it
* Pricing wise for a basic general purpose instance we're looking at approximately £120 per month + dev/sandbox environment costs of approximately £30 per month. These estimates are not based on real usage and may increase

Azure SQL Server
* We already use this for the keycloak database, and because of Microsoft's support of the underlying SQL Server product would have been my preference, however the container documentation doesn't report support for Microsoft SQL Server, however the underlying products seem to indicate that they do support it but we may need to make customisations to the container images to support this.
* We will need to figure out how to build the MSSQL database and deploy it
* Pricing wise for a standard 100 DTU instance we're looking at approximately £150 per month + dev/sandbox environment costs of approximately £30 per month (for 10 DTU). These estimates are not based on real usage and may increase 

In all cases we can potentially reduce costs by reserving instances.

Please let me know how you would like me to proceed

**Comment by vvcb** [comment]
@qcaas-nhs-sjt , I think OHDSI stopped support for anything but Postgres as the backend application database for ATLAS/WebAPI a few years ago. I will find the relevant URL with that information.

 So, Postgres it is.

Where this is hosted is an important but secondary issue that we can visit once we have the rest of the stack up and running.

For now, let's use the Postgres deployment as part of the OHDSI Helm chart backed by Azure file share.

I suspect by the time we have everything up and running and plugged into our OMOP data (and this will be quite the journey), the dust around the Postgres offerings in Azure should have settled.

**Comment by qcaas-nhs-sjt** [comment]
after further discussion a postgresql single server was decided upon for the time being. this has been implemented and is tested and working
